[tool.poetry]
name = "artifaq"
version = "0.1.0"
description = ""
authors = ["lguerra <l.guerra--rago@xefi.fr>"]
license = "Apache"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
